# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a38f9d24be5baedbde4d2dff8dedc2debc5d285bb092d0fb75886309cf7d03bc2fe0932d5b86723cda3071a2e4a9a16eac5e4340b665e2d610fdc910d31c4a0

test:
  secret_key_base: 2611b4b30509f56507ad6ea444f9552ac24508886045f1cc8d42080fa340ad2cb8281905de23bf10c85f4927d04a15d7d8ddc1a796cefb6a52e568e2c4ebf7d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
